tests: config/tests-cases.yaml
runs_per_test: 1
models:
  # OpenAI models
  - name: "gpt-3.5-turbo"
  - name: "gpt-3.5-turbo-16k"
  - name: "gpt-4"
  - name: "gpt-4-turbo"
  - name: "gpt-4.1"
  - name: "gpt-4.1-mini"
  - name: "gpt-4o"
  - name: "gpt-4o-mini"
  - name: "gpt-4o-mini-realtime-preview"
  - name: "gpt-4o-realtime-preview"
  - name: "o1-mini"
  - name: "o3"
  - name: "o3-mini"
  - name: "o4-mini"
  - name: "gpt-5"
  - name: "gpt-5-mini"
  - name: "gpt-5-nano"
  # Anthropic Claude models
  - name: "claude-opus-4-1-20250805"
  - name: "claude-opus-4-20250514"
  - name: "claude-sonnet-4-20250514"
  - name: "claude-3-7-sonnet-20250219"
  - name: "claude-3-5-haiku-20241022"
  - name: "claude-3-haiku-20240307"
