# Registry of models. Keys should be stable names you use in tests & harness.
models:
  # ---- Local / test doubles -------------------------------------------------
  echo-local:
    provider: echo
    endpoint: mock://echo
    api_key: ${OPENAI_API_KEY:-dummy}
    timeout_s: 5

  mock-gpt:
    provider: mock
    endpoint: mock://local
    api_key: ${MOCK_API_KEY:-dummy}
    timeout_s: 10

  # ---- OpenAI (legacy Chat Completions endpoint) ----------------------------
  # These models are accessed via /v1/chat/completions
  gpt-3.5-turbo:
    provider: openai
    endpoint: https://api.openai.com/v1/chat/completions
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-3.5-turbo-16k:
    provider: openai
    endpoint: https://api.openai.com/v1/chat/completions
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-4:
    provider: openai
    endpoint: https://api.openai.com/v1/chat/completions
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-4-turbo:
    provider: openai
    endpoint: https://api.openai.com/v1/chat/completions
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  # ---- OpenAI (Responses endpoint) -----------------------------------------
  # Newer models are served via /v1/responses
  gpt-4.1:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-4.1-mini:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-4o:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-4o-mini:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-4o-mini-realtime-preview:
    provider: openai-realtime
    endpoint: https://api.openai.com/v1/realtime/sessions
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-4o-realtime-preview:
    provider: openai-realtime
    endpoint: https://api.openai.com/v1/realtime/sessions
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  o1-mini:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  o3:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  o3-mini:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  o4-mini:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  # ---- GPT-5 family (availability varies by account) -----------------------
  # If your key doesn't have access yet, these will error.
  gpt-5:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-5-mini:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  gpt-5-nano:
    provider: openai
    endpoint: https://api.openai.com/v1/responses
    api_key: ${OPENAI_API_KEY}
    timeout_s: 30

  # ---- Anthropic Claude models ------------------------------------------------
  # Claude models via Anthropic API
  claude-opus-4-1-20250805:
    provider: anthropic
    endpoint: https://api.anthropic.com/v1/messages
    api_key: ${ANTHROPIC_API_KEY}
    timeout_s: 30

  claude-opus-4-20250514:
    provider: anthropic
    endpoint: https://api.anthropic.com/v1/messages
    api_key: ${ANTHROPIC_API_KEY}
    timeout_s: 30

  claude-sonnet-4-20250514:
    provider: anthropic
    endpoint: https://api.anthropic.com/v1/messages
    api_key: ${ANTHROPIC_API_KEY}
    timeout_s: 30

  claude-3-7-sonnet-20250219:
    provider: anthropic
    endpoint: https://api.anthropic.com/v1/messages
    api_key: ${ANTHROPIC_API_KEY}
    timeout_s: 30

  claude-3-5-haiku-20241022:
    provider: anthropic
    endpoint: https://api.anthropic.com/v1/messages
    api_key: ${ANTHROPIC_API_KEY}
    timeout_s: 30

  claude-3-haiku-20240307:
    provider: anthropic
    endpoint: https://api.anthropic.com/v1/messages
    api_key: ${ANTHROPIC_API_KEY}
    timeout_s: 30