# Simplified test run configuration
# Automatically runs all tests from tests.yaml against specified models
runs_per_test: 100  # Default number of runs per test

models:
  # OpenAI models
  - name: "gpt-3.5-turbo"
  - name: "gpt-3.5-turbo-16k"
  - name: "gpt-4"
  - name: "gpt-4.1"
  - name: "gpt-4.1-mini"
  - name: "gpt-4o"
  - name: "gpt-4o-mini"
  - name: "o3"
  - name: "o3-mini"
  - name: "o4-mini"
  - name: "gpt-5"
  - name: "gpt-5-mini"
  - name: "gpt-5-nano"
  - name: "gpt-4o-mini-realtime-preview"
  - name: "gpt-4o-realtime-preview"