# Full test run configuration with all supported models
# Automatically runs all tests from tests-cases.yaml against specified models
tests: config/tests-cases-added.yaml
runs_per_test:  1  # Default number of runs per test (reduced for comprehensive testing)

models:
      # Real-time preview models
  - name: "gpt-4o-mini-realtime-preview"
  - name: "gpt-4o-realtime-preview"
