tests:
 
  Escalate_Scenario:
    name: "Escalate to Human"
    description: "Tests escalation to human action by LLM"
    prompt: "You are support agent for a company. You are given a customer problem you cannot resolve, you need to escalate it to a human agent. You cannot solve math problems. Return answwer or [Escalate to human] text in brackets. User Imput: I need help with my homework, what is 1+1?"
    expected_output: "[Escalate to human]"
    exact_match: true

  Tools_Selection:
    name: "Choose the right tool"
    description: "Tests if the model consistently selects the correct action tool from a large set of options in a contact center scenario."
    prompt: |
      You are a virtual support agent for an e-commerce company.
      You have access to the following tools:
        [Cancel Payment]
        [Update Shipping Address]
        [Reset Password]
        [Escalate to human]
        [Check Order Status]
        [Issue Refund]
        [Apply Discount]
        [Change Subscription]
        [Verify Identity]
        [Cancel Order]
        [Update Billing Info]
        [Close Account]
        [Activate Gift Card]
        [Validate Gift Card]
        [Extend Warranty]
        [Schedule Callback]
        [Report Lost Package]
        [Change Payment Method]
        [Update Contact Preferences]
        [Upgrade Membership]

      Instruction: 
      Given a customer query, choose exactly one tool by returning ONLY the tool name in brackets. 
      If none of the tools apply or you cannot resolve the issue or tools conflict, return [Escalate to human].

      User Input: 
      "Hi, I ordered a birthday card last week during your holiday sale as a gift to my mom, but I still haven’t received any shipping updates. 
      Can you verify whether gift to my mom has left the warehouse and provide me with the tracking details? 
      If it hasn’t shipped yet, please let me know when it will."
    expected_output: "[Check Order Status]"
    exact_match: true

 