# Simplified test run configuration
# Automatically runs all tests from tests.yaml against specified models
tests: config/tests.yaml
runs_per_test: 2  # Default number of runs per test

models:
  # OpenAI models
  - name: "gpt-3.5-turbo"
  - name: "claude-opus-4-1-20250805"

