# Simplified test run configuration
# Automatically runs all tests from tests.yaml against specified models
runs_per_test: 5  # Default number of runs per test

models:
  # OpenAI models
  - name: "gpt-3.5-turbo"
  - name: "gpt-4"
  - name: "gpt-4.1"
  - name: "gpt-4.1-mini"
  - name: "gpt-4o"
  - name: "gpt-4o-mini"
  - name: "o3"
  - name: "o4-mini"
  - name: "gpt-5"
  - name: "gpt-5-mini"
  - name: "gpt-5-nano"
